### ISSUE TITLE
IMU data

### ISSUE THREAD

**Issue by vatsalkshah** [arnefmeyer/IMUReaderPlugin#1]
@arnefmeyer  Where do I find the csv file imu_data.csv?

**Comment by arnefmeyer** [comment]
in the recording base directory, i.e. the location returned by "CoreServices::RecordNode::getRecordingPath()". For the binary format this is the directory containing the "settings.xml" file and the "experimentX" folder (where X depends on your current experiment number). Just to avoid confusion with upper/lower cases: the file you are looking for is "IMU_data.csv" rather than "imu_data.csv". If the file has not been created check if the IMU reader is displaying a meaningful FPS value (> 0, typically > 150 Hz depending on your system/microcontroller/IMU) while recording data.
